Algoritmo "Calculos"
Var
   N1, N2, N3, N4, S: inteiro
   M: Real

Inicio
   Escreva ("Informe um numero: ")
   Leia (N1)
   Escreva ("Informe outro numero: ")
   Leia (N2)
   S <- N1 + N2
   Escreval ("A soma entre", N1, " e", N2, " e igual a:", S)
   
   Escreval ("Proximo Calculo")
   Escreval ("Digite um Numero")
   Leia (N3)
   Escreval ("Digite outro Numero")
   Leia (N4)
   
   M <- (N3 + N4) / 2
   
   Escreva ("A media entre", N3, " e", N4, " e igual a", M)
   

Fimalgoritmo